imports:
    - php

filter:
    paths: [src/*]

build_failure_conditions:
    - 'issues.label("coding-style").exists'
    - 'project.metric("scrutinizer.test_coverage", < 1)'

tools:
    external_code_coverage: true
    php_cs_fixer:
        enabled: true
        command: vendor/bin/phpcs --standard=PSR2 -s -p src/
        config:
            level: psr2