language: php

php:
    - 5.4
    - 5.5
    - hhvm

before_script:
    - composer self-update
    - composer update

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit -c test/phpunit.xml --coverage-clover=./build/clover.xml
    - vendor/bin/spiffy-cc build/clover.xml 100